apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: <namespace_name>
  name: te-<node_zone_name>
  labels:
    group: nuodb
spec:
  replicas: 2
  selector:
    matchLabels:
     app: te
  template:
    metadata:
      labels:
        app: te
    spec:
      containers:
      - name: te-<node_zone_name>
        image: docker.io/nuodb/nuodb-ee:3.3.0-master-5611
        env:
        - name: API_PORT
          value: "8888"
        - name: PEER_ADDRESS
          value: <admin_service_name>
        - name: DB_NAME
          value: hockey
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: nuodb-secret
              key: database-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nuodb-secret
              key: database-password
        - name: NODE_REGION
          value: <node_zone_name>
        - name: NODE_TYPE
          value: TE
      imagePullSecrets:
      - name: regcred