apiVersion: v1
kind: Service
metadata:
  namespace: <namespace_name>
  annotations:
    "service.alpha.kubernetes.io/tolerate-unready-endpoints": "true"
  labels:
    group: nuodb
    app: nuodb
  name: nuoadmin-dns
spec:
  clusterIP: None
  ports:
  - name: none
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    dns: nuoadmin
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: <namespace_name>
  annotations:
    description: "Service for Admin pods."
  labels:
    group: nuodb
    app: nuodb
  name: <admin_service_name>
spec:
  ports:
  - name: 8888-tcp
    port: 8888
    protocol: TCP
    targetPort: 8888
  - name: 48004-tcp
    port: 48004
    protocol: TCP
    targetPort: 48004
  - name: 48005-tcp
    port: 48005
    protocol: TCP
    targetPort: 48005
  selector:
    app: admin
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  namespace: <namespace_name>
  name: nuoadmin-<node_zone_name>
  labels:
    group: nuodb
spec:
  serviceName: "nuoadmin-dns"
  replicas: 3
  selector:
    matchLabels:
     dns: nuoadmin
     app: admin
  template:
    metadata:
      labels:
        dns: nuoadmin
        app: admin
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - admin
              topologyKey: kubernetes.io/hostname
      containers:
      - name: nuoadmin-<node_zone_name>
        image: docker.io/nuodb/nuodb-ee:3.3.0-master-5609
        ports:
        - containerPort: 8888
          name: api
          protocol: TCP
        - containerPort: 48004
          protocol: TCP
        - containerPort: 48005
          protocol: TCP
        env:
        - name: DNS_LOOKUP
          value: nuoadmin-dns
        - name: API_PORT
          value: "8888"
        - name: PEER_ADDRESS
          value: <admin_service_name>
        - name: NODE_REGION
          value: <node_zone_name>
        - name: NODE_TYPE
          value: NUOADMIN
        - name: FIRST_CLUSTER_API
          value:
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 2
          failureThreshold: 30
          successThreshold: 2
          timeoutSeconds: 1
          httpGet:
            path: /api/1/peers
            port: 8888
      imagePullSecrets:
      - name: regcred