apiVersion: v1
kind: Secret
metadata:
  namespace: demo
  name: nuodb-secret
  labels: group: nuodb
type: Opaque
data:
  database-username: Z29hbGll
  database-password: Z29hbCE=
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: demo
  name: sm-us-east-2a
  labels:
    group: nuodb
spec:
  replicas: 1
  selector:
    matchLabels:
     app: sm
  template:
    metadata:
      labels:
        app: sm
    spec:
      containers:
      - name: sm-us-east-2a
        image: docker.io/nuodb/nuodb-ee:3.3.0-1548
        ports:
        - containerPort: 8888
          name: api
          protocol: TCP
        - containerPort: 48004
          protocol: TCP
        - containerPort: 48005
          protocol: TCP
        env:
        - name: API_PORT
          value: "8888"
        - name: PEER_ADDRESS
          value: "nuodb-svc"
        - name: DB_NAME
          value: hockey
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: nuodb-secret
              key: database-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nuodb-secret
              key: database-password
        - name: NODE_REGION
          value: us-east-2a
        - name: NODE_TYPE
          value: SM
        volumeMounts:
        - mountPath: /archive
          name: sm-archives-us-east-2a
        - mountPath: /journal
          name: sm-journal-us-east-2a
      volumes:
      - name: sm-archives-us-east-2a
        hostPath:
          path: /local-storage/archive
      - name: sm-journal-us-east-2a
        hostPath:
          path: /local-storage/journal
      imagePullSecrets:
      - name: regcred