apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: toolkit
  labels:
    template: toolkit
  annotations:
    openshift.io/display-name: "NuoDB Toolkit"
    description: "NuoDB Toolkit and YCSB load generator"
    iconClass:
    tags: "database,nuodb"
    openshift.io/provider-display-name: "NuoDB, Inc."
    openshift.io/documentation-url: "http://doc.nuodb.com/Latest/Default.htm"
    openshift.io/support-url: "https://support.nuodb.com/hc/en-us"
    message: "The following service(s) have been created in your project: placeholder."
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: "Toolkit container"
      template.alpha.openshift.io/wait-for-ready: "true"
    labels:
      app: toolkit
    name: ${DEPLOYMENTCONFIG}
  spec:
    replicas: 1
    selector:
      app: toolkit
      deploymentconfig: ${DEPLOYMENTCONFIG}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 100%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        labels:
          app: toolkit
          deploymentconfig: ${DEPLOYMENTCONFIG}
      spec:
        nodeSelector:
          zone: ${NODE_REGION}
        containers:
        - env:
          - name: YCSB_WORKLOAD
            value: ${YCSB_WORKLOAD}
          - name: AGENT_PORT
            value: "8888"
          - name: PEER_ADDRESS
            value: ${ADMIN_SVC_NAME}-${NODE_REGION}
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: ${SECRET_NAME}
                key: database-name
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: ${SECRET_NAME}
                key: database-username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${SECRET_NAME}
                key: database-password
          - name: NODE_REGION
            value: local
          - name: NODE_TYPE
            value: toolkit
          image: ${CONTAINER}
          imagePullPolicy: IfNotPresent
          name: toolkit
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /archive
            name: toolkit-volume-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        volumes:
        - emptyDir: {}
          name: toolkit-volume-1
parameters:
  - name: NAMESPACE
    displayName: Namespace
    description: "The OpenShift Namespace where the ImageStream resides."
    value: openshift
  - name: DEPLOYMENTCONFIG
    displayName: Deployment Config Name
    description: "Unique name for the Pod deployment"
    required: true
    value: toolkit
  - name: YCSB_WORKLOAD
    displayName: YCSB Workload
    description: "Run YCSB workload against your database. Valid workload options are [a|b|c|d|e|f|g]. Leave blank if using just the Toolkit"
  - name: NODE_REGION
    displayName: Deployment Zone
    description: "Deploy NuoDB to labeled OpenShift Nodes"
    required: true
    value: default
  - name: ADMIN_SVC_NAME
    displayName: NuoDB Admin Service Name
    description: "Service Name to Connect to NuoAdmin. Node region parameter will be appended to string"
    required: true
    value: nuodb-svc
  - name: SECRET_NAME
    displayName: Secret Name
    description: "Name of Secret to store database username and password"
    required: true
    value: nuodb-secret
  - name: CONTAINER
    displayName: Container Registry
    description: "Registry to pull NuoDB from."
    required: true
    value: "docker.io/nuodb/nuodb-ee:toolkit-3.1.1-10.7"

